#!/usr/bin/env bash

paru -S waybar
sudo pacman -S python-requests
sudo pacman -S wl-clipboard
sudo pacman -S ttf-jetbrains-mono-nerd
sudo pacman -S pulseaudio pulseaudio-alsa
sudo pacman -S pavucontrol paprefs pulseaudio-bluetooth
paru -S pamixer
